sudo: required
service:
    - docker

script:
    - docker build -t jordanmom/node2 .
    - docker images jordanmom/node2

before_deploy:
    - docker login -u jordanmom -p D3lt4/SSSS

deploy:
    provider: script
    script: docker push jordanmom/testnode
    on:
        branch: main